### ISSUE TITLE
360安全浏览器访问Nginx时出现一分钟后重启的问题

### ISSUE THREAD

**Issue by bjgxjob** [jntass/Nginx_Tassl#10]
360安全浏览器访问Nginx时出现一分钟后重启的问题

Nginx：Nginx_Tassl-master.zip  从Master下载的
TASSL：TASSL-1.1.1b

360浏览器：12.2.1218.0
其它支持国密浏览器： 可以访问Nginx上的页面

现象：
在Windows 10 上，将根证书按360论坛的要求配置到CTL目录。 使用360浏览器通过HTTPS访问Nginx，会出现如附图的现象。

![微信图片_20200709165852](https://user-images.githubusercontent.com/16394199/87020387-59c69400-c206-11ea-9077-3ddb07b09cf3.jpg)

**Comment by jntass** [comment]
修改hosts,  C:\Windows\System32\drivers\etc,  将测试服务器地址 指向一个域名，例如abc，使用域名abc访问。
此问题为360浏览器的问题。

**Comment by bjgxjob** [comment]
按你的指导，已经解决该问题。
谢谢你！
