### ISSUE TITLE
编译安装后启动失败，找不到tasscard_sm4.so，请问该怎么解决

### ISSUE THREAD

**Issue by gdlwl** [jntass/Nginx_Tassl#11]
[root@192 ~]# nginx -c /root/nginx/conf/nginx.conf
#报错信息
the error = [/root/lib_r/tassl/lib/engines-1.1/tasscard_sm4.so: cannot open shared object file: No such file or directory]
nginx: [emerg] ENGINE load id=[tasscard_sm4] failed

#查看/root/lib_r/tassl/lib/engines-1.1目录只有capi.so  padlock.so两个文件
[root@192 engines-1.1]# ls /root/lib_r/tassl/lib/engines-1.1
capi.so  padlock.so

**Comment by jntass** [comment]
需要修改你的nginx.conf文件中关于ssl_tass_sm4为off；这个是调用我们的加密卡进行sm4计算的引擎，你没有加密卡的话，需要关闭。
![image](https://user-images.githubusercontent.com/34365704/87494561-eac3c200-c681-11ea-86b1-ee59542ba30d.png)
